### PR TITLE
❤️  U guys

### PR DESCRIPTION
**Pull request by HarmonicPool**

### CODE REVIEW

**Comment by cxhercules** [comment]
We are not able to connect to backend service. 

I have tried a simple curl validation and it does not want to connect:
```
curl -s -o /dev/null -w ''%{http_code}'' -X POST -H ''Content-Type: application/cbor'' http://harmonicrelay.mooo.com:8090/api/submit/tx
```

**Comment by envystakepool** [comment]
Right back at you! We're discussing CORS issue with HAproxy and will approve when we fix the issue. THanks for your patience!

**Comment by cxhercules** [comment]
Reach out if you want to troubleshoot this

**Comment by cxhercules** [comment]
Please open up firewall

**Comment by cxhercules** [comment]
https://twitter.com/adacoinz/status/1559047741333942272?s=20&t=CCmqGKKUPc1voDd3A-uSmQ Reached out. @EtherealStakePool

**Comment by HarmonicPool** [comment]
hey thank you for the patience; I'm sorry I didn't mind checking my bad;
thanks for your help now it should be solved

**Comment by skelly433** [comment]
Your endpoint worked Michele!

**Comment by envystakepool** [comment]
Closing because I made a branch PR of this submission.

**Pull request closed without merging**
