### PR TITLE
ip update

### PR DESCRIPTION
**Pull request by lucifer911**
Changing DDNS to an IP

### CODE REVIEW

**Comment by envystakepool** [comment]
Tested twice on my Nami wallet and it failed. Can you check your firewall settings?

**Comment by cxhercules** [comment]
I have also tested from load balancers and it is not communicating. It is timing out.

**Comment by lucifer911** [comment]
MY IP keeps getting changed. I am using a DNS record. Can you try pinging that? api.cr0ss0ver.com

**Comment by cxhercules** [comment]
I get this when I try to ping:
```
ping api.cr0ss0ver.com
PING api.cr0ss0ver.com (76.69.2.225) 56(84) bytes of data.
```

which is a different IP. Why don't you use the dns name, or dynamic dns our service is setup to detect IP changes to dns and will redirect traffic.

**Comment by cxhercules** [comment]
But when I try to hit the endpoint it is closed? I get basically a connection closed right away for:
```
nc: connect to api.cr0ss0ver.com (76.69.2.225) port 8090 (tcp) failed: Connection refused
```

**Comment by cxhercules** [comment]
Never resolved

**Pull request closed without merging**
